export const projectArr = [
  {
    name: "Recycle Computer",
    url: "/foto/recycleComputer.png",
    text: "",
    title: "Recycle Computer",
    link: "https://gmcomputerrecycle.com",
  },

  {
    name: "Klimra App",
    url: "/foto/klimra.png",
    text: "",
    title: "Klimra App",
    link: "https://klimra.com",
  },
  {
    name: "jul handle",
    url: "/foto/handleProducts.png",
    text: "",
    title: "Jul Handle App",
    link: "https://github.com/josephkhella2010/jul-handel-application-nodejs-react-typescript",
  },
  {
    name: "bookList",
    url: "/foto/bookList.png",
    text: "",
    title: "BookList App",
    link: "https://github.com/josephkhella2010/crud--with-flask-mongo-db-and-react",
  },
  {
    name: "wallet",
    url: "/foto/wallet.png",
    text: "",
    title: "Wallet App",
    link: "https://github.com/josephkhella2010/wallet-projekt-med-react",
  },
  {
    name: "Create and Filter Items",
    url: "/foto/nextjs.png",
    text: "",
    title: "Create and Filter Items App",
    link: "https://github.com/josephkhella2010/nextjsproject",
  },
  {
    name: "Quiz",
    url: "/foto/quiz.png",
    text: "",
    title: "Quiz App",
    link: "https://github.com/josephkhella2010/Quiz-with-react",
  },
  {
    name: "pokemonGame",
    url: "/foto/pokemonGame.png",
    text: "",
    title: "PokemonGame App",
    link: "https://github.com/josephkhella2010/pokemon-application",
  },
  {
    name: "todoList",
    url: "/foto/todoList.png",
    text: "",
    title: "TodoList App",
    link: "https://github.com/josephkhella2010/todo-react",
  },
];
